language: cpp

dist: xenial # default distribution
os: linux # default os
sudo: false


env:
  - CXXFLAGS=-std=c++11
  - CXXFLAGS=-std=c++14
  - CXXFLAGS=-std=c++17

matrix:
  fast_finish: true
  include:
    - env: MATRIX_EVAL="CC=gcc-5 && CXX=g++-5 && GENERATOR='Unix Makefiles'"
      addons: { apt: { packages: ["g++-5"], sources: ["ubuntu-toolchain-r-test"] } }

    - env: MATRIX_EVAL="CC=gcc-6 && CXX=g++-6 && GENERATOR='Unix Makefiles'"
      addons: { apt: { packages: ["g++-6"], sources: ["ubuntu-toolchain-r-test"] } }

    - env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && GENERATOR='Unix Makefiles'"
      addons: { apt: { packages: ["g++-7"], sources: ["ubuntu-toolchain-r-test"] } }

    - env: MATRIX_EVAL="CC=gcc-8 && CXX=g++-8 && GENERATOR='Unix Makefiles'"
      addons: { apt: { packages: ["g++-8"], sources: ["ubuntu-toolchain-r-test"] } }

    - env: MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0 && GENERATOR='Unix Makefiles'"
      addons: { apt: { packages: ["clang-5.0"] } }

    - env: MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0 && GENERATOR='Unix Makefiles'"
      addons: { apt: { packages: ["clang-6.0"] } }

    - env: MATRIX_EVAL="CC=clang-7 && CXX=clang++-7 && GENERATOR='Unix Makefiles'"
      addons: { apt: { packages: ["clang-7", "libc++-7-dev", "libc++abi-7-dev"], sources: ["llvm-toolchain-xenial-7"] } }

    - env: MATRIX_EVAL="CC=clang-8 && CXX=clang++-8 && GENERATOR='Unix Makefiles'"
      addons: { apt: { packages: ["clang-8", "libc++-8-dev", "libc++abi-8-dev"], sources: ["llvm-toolchain-xenial-8"] } }

    - os: osx
      env: MATRIX_EVAL="CC=clang && CXX=clang++ && GENERATOR=Xcode"
      osx_image: xcode9.2

install:
  - eval "${MATRIX_EVAL}"
  - |
    if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew update
      brew upgrade cmake
    fi
  - $CC --version
  - $CXX --version
  - cmake --version

before_script:
  - mkdir build
  - cd build
  - export VERBOSE=1
  - cmake -G"${GENERATOR}" -DCMAKE_CXX_COMPILER="${CXX}" -DCMAKE_C_COMPILER="${CC}" -DCMAKE_CXX_FLAGS="${CXXFLAGS}" ..

script:
  - export VERBOSE=1
  - cmake --build . --config Release
  - ctest
